# Generated by Django 5.2.1 on 2025-07-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactcard',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactcard',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactcard',
            old_name='Name',
            new_name='name',
        ),
    ]
